server:
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/890db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: hyoung135!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

aws:
  s3:
    bucketName: health-lounge890


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace


